version: "3"

services:
  school:
    environment:
      - DB_HOST=db
      - DB_NAME=school_db
      - DB_USER=postgres
      - DB_PASS=superkey
    depends_on:
      - db
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./school:/school
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=school_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superkey
    ports:
      - "5432:5432"
    hostname: db